### ISSUE TITLE
update to support M1 silicon?

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaBinaryWrappers/coordgenlibs_jll.jl#1]
hi. `MolecularGraph.jl` depends on `coordgenlibs_jll.jl`, but it seems M1 Silicon isn't supported. how can we update this repo to support M1 silicon? thanks!

e.g.

```julia
using coordgenlibs_jll
minmol = ccall((:getSketcherMinimizer, libcoordgen), Ptr{Cvoid}, ())
# ERROR: UndefVarError: libcoordgen not defined
```

https://github.com/mojaie/MolecularGraph.jl/issues/64

**Comment by mojaie** [comment]
coordgenlibs_jll 3.0.1+0 was built yesterday. It was built for also aarch64-apple-darwin, so I hope it works with Apple silicon.

**Comment by mojaie** [comment]
Yes, coordgenlibs_jll 3.0.1+0 will be applied in the next version of MolecularGraph.jl.
If you have still error in the above code, could you check coordgenlibs_jll version by `] status`, and if it is not 3.0.1+0, could you try `] rm coordgenlibs_jll` and `] add coordgenlibs_jll` ?
Perhaps `[compat]` in Project.toml should be changed from `coordgenlibs_jll = "1.4"` to `coordgenlibs_jll = "3.0"`

**Comment by SimonEnsemble** [comment]
ah, `MolecularGraph` was holding `coordgenlibs_jll` back 😆 .
now `] status` is `coordgenlibs_jll v3.0.1+0` and the code in my first post runs, woo-hoo! thanks.
hope `MolecularGraph`  will support the new version soon!
